export const columnData1 = [
    { x: 'GBR', y: 27, toolTipMappingName: 'Great Britain' },
    { x: 'CHN', y: 26, toolTipMappingName: 'China' },
    { x: 'AUS', y: 8, toolTipMappingName: 'Australia' },
    { x: 'RUS', y: 19, toolTipMappingName: 'Russia' },
    { x: 'GER', y: 17, toolTipMappingName: 'Germany' },
    { x: 'UA', y: 2, toolTipMappingName: 'Ukraine' },
    { x: 'ES', y: 7, toolTipMappingName: 'Spain' },
    { x: 'UZB', y: 4, toolTipMappingName: 'Uzbekistan' },
    { x: 'JPN', y: 12, toolTipMappingName: 'Japan' },
    { x: 'NL', y: 8, toolTipMappingName: 'NetherLand' },
    { x: 'USA', y: 46, toolTipMappingName: 'United States' },
];
export const columnData2 = [
    { x: 'GBR', y: 23, toolTipMappingName: 'Great Britain' },
    { x: 'CHN', y: 18, toolTipMappingName: 'China' },
    { x: 'AUS', y: 11, toolTipMappingName: 'Australia' },
    { x: 'RUS', y: 17, toolTipMappingName: 'Russia' },
    { x: 'GER', y: 10, toolTipMappingName: 'Germany' },
    { x: 'UA', y: 5, toolTipMappingName: 'Ukraine' },
    { x: 'ES', y: 4, toolTipMappingName: 'Spain' },
    { x: 'UZB', y: 2, toolTipMappingName: 'Uzbekistan' },
    { x: 'JPN', y: 8, toolTipMappingName: 'Japan' },
    { x: 'NL', y: 7, toolTipMappingName: 'NetherLand' },
    { x: 'USA', y: 37, toolTipMappingName: 'United States' },
];
export const columnData3 = [
    { x: 'GBR', y: 17, toolTipMappingName: 'Great Britain' },
    { x: 'CHN', y: 26, toolTipMappingName: 'China' },
    { x: 'AUS', y: 10, toolTipMappingName: 'Australia' },
    { x: 'RUS', y: 20, toolTipMappingName: 'Russia' },
    { x: 'GER', y: 15, toolTipMappingName: 'Germany' },
    { x: 'UA', y: 24, toolTipMappingName: 'Ukraine' },
    { x: 'ES', y: 6, toolTipMappingName: 'Spain' },
    { x: 'UZB', y: 7, toolTipMappingName: 'Uzbekistan' },
    { x: 'JPN', y: 8, toolTipMappingName: 'Japan' },
    { x: 'NL', y: 4, toolTipMappingName: 'NetherLand' },
    { x: 'USA', y: 38, toolTipMappingName: 'United States' },
];
